In [28]:
import tensorflow as tf
import numpy as np
from tensorflow.python import keras
import pandas as pd

iris_org=pd.read_csv("../data/iris.csv")
#help(irist.drop)
iris_org.drop(['no'],1,inplace=True)
# Shuffling
iris=iris_org.sample(frac=1).reset_index(drop=True)

# Basic Encoding & One-hot Encoding

In [30]:
labels=iris['Species']
labels.head(10)

0        setosa
1    versicolor
2        setosa
3     virginica
4     virginica
5        setosa
6        setosa
7     virginica
8     virginica
9    versicolor
Name: Species, dtype: object

In [38]:
sets=labels.drop_duplicates().tolist()
encoder={k:v for v,k in enumerate(sets)}
lablels_encoded=[ encoder[i] for i in labels.tolist() ]
lablels_encoded[:10]

[0, 1, 0, 2, 2, 0, 0, 2, 2, 1]

In [50]:
lablels_one_hot_encoded = keras.utils.to_categorical(lablels_encoded, 3)
lablels_one_hot_encoded[:10]

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

# Binary Encoding

In [83]:
su=11
su_bin=format(f'{i:#b}')
su_bin
[i for i in su_bin[2:]]

['1', '0', '1', '1']

In [164]:
def bin_encoder(su,width=8):
    ones=np.zeros([width])
    su_bin=format(f'{su:#b}')
    encoded_data=[i for i in su_bin[2:]]
    s=width-len(encoded_data)
    ones[s:width]=encoded_data
    return (ones)

bin_encoder(11)

array([0., 0., 0., 0., 1., 0., 1., 1.])

In [146]:
data1=pd.Series([0,2,4,8,255])
data1_bin_encoded=[bin_encoder(i) for i in data1]
data1_bin_encoded

[array([0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.])]

# Range Encoding 예
* 값의 범위가 너무 클때
*   x<10 →  [ 1, 0, 0, 0 ] ,  x<100 → [ 0, 1, 0, 0 ],   x<1000 →  [ 0, 0, 1, 0  ] , x=>1000 →  [ 0, 0, 0, 1]

In [181]:
data2=pd.Series([1,11,111,1111,11111111111])


def range_encoder(su):
    triggers=[10,100,1000,float('inf')]
    tc=len(triggers)
    e=np.eye(tc)
    for i in range(tc):
        if su < triggers[i]:
            ret = e[i]
            break
    return(ret)

range_encoder(11)    

array([0., 1., 0., 0.])

In [182]:
data2_range_encoded = [ range_encoder(i) for i in data2]
data2_range_encoded

[array([1., 0., 0., 0.]),
 array([0., 1., 0., 0.]),
 array([0., 0., 1., 0.]),
 array([0., 0., 0., 1.]),
 array([0., 0., 0., 1.])]