# Numpy instrospection

In [1]:
import math

In [2]:
import numpy as np

In [3]:
# dir(np)
# dir(math)
# help(np.array)
# print('\n'.join([s for s in dir(np) if s.find('array') >= 0 ]))

# Operation
## Plus 연산

In [4]:
a1=np.array([1, 2, 3])
a2=np.array([1, 1, 1])
a1+a2

array([2, 3, 4])

## Dot product

In [5]:
a1=np.array([[1, 2],[3,4]])
a2=np.array([[2, 0],[0,2]])
# a1*a2
np.dot(a1,a2)

array([[2, 4],
       [6, 8]])

# Cf) join, for-in 문

In [6]:
#dir("x")
"x".join(['1','2','3'])

'1x2x3'

In [7]:
[i*2 for i in range(10) if i%2 == 0 ]

[0, 4, 8, 12, 16]

# Shape

In [8]:
a1=np.array([[1, 2, 3],[4,5,6]])
a1.shape


(2, 3)

# Reshape

In [9]:
a2=np.array(range(12))
a2.reshape((3,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Random

In [10]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [11]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [12]:
m=np.random.randn( 2,3)
print(m)

[[-0.28405595  0.73819287 -1.11523758]
 [ 0.69571747 -0.67675976 -0.81295688]]


# 방정식 풀기

In [13]:
#help(np.linalg.inv)
np.linalg.inv(np.array([[2, 0],
                        [0, 2]]))

array([[0.5, 0. ],
       [0. , 0.5]])

In [14]:
# y=2x+1, y=-x+1
a=np.array([[1, -2],[1,1]])

ai= np.linalg.inv(a)
np.dot(ai,np.array([[1],[4]]))



array([[3.],
       [1.]])